@startuml
class Cliente {
  + id: int
  + nombre: string
  + direccion: string
  + telefono: string
  + email: string
  + historialMedico: string
  + registrarCliente()
  + actualizarCliente()
}

class Membresia {
  + id: int
  + tipo: string
  + fechaInicio: date
  + fechaFin: date
  + estado: string
  + planPago: PlanDePago
  + cliente: Cliente
  + renovarMembresia()
  + calcularDescuento()
}

class Pago {
  + id: int
  + fecha: date
  + monto: float
  + metodoPago: string
  + membresia: Membresia
  + generarFactura()
}

class Factura {
  + id: int
  + fecha: date
  + monto: float
  + detalle: string
  + pago: Pago
}

class Notificacion {
  + id: int
  + fecha: date
  + tipo: string
  + mensaje: string
  + cliente: Cliente
  + enviarNotificacion()
}

class PlanDePago {
  + id: int
  + tipo: string
  + costo: float
  + duracion: int
}

' Relaciones entre las clases
Cliente -- Membresia
Membresia *-- Pago
Pago *-- Factura
Cliente o-- Notificacion
Membresia o-- PlanDePago

@enduml